### ISSUE TITLE
startBlock=13547115: how do we tell?

### ISSUE THREAD

**Issue by 0xbe1** [dabit3/ethdenver-workshop#1]
Hi @dabit3 - I am curious how do you decide to have startBlock=13547115?

Thanks!

**Comment by dabit3** [comment]
Hi, yes the start block is usually when the first transaction is processed in the network from this smart contract, you can usually find it in the block explorer.

**Comment by 0xbe1** [comment]
Interesting, now I find it:

https://etherscan.io/txs?a=0x5180db8f5c931aae63c74266b211f580155ecac8&p=189

Thank you Nader @dabit3
